# base php-apache image
FROM php:8.5-apache

# set container working directory
WORKDIR /var/www

# install required packages
RUN apt-get update && apt-get install -y \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libicu-dev \
    libpng-dev \
    rpm

# install PHP extensions
RUN docker-php-ext-install pdo_mysql intl

# install phpGD extension
RUN docker-php-ext-configure gd \
    && docker-php-ext-install -j$(nproc) gd
